name: Build and Push Docker Image

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up JDK 25
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '25'

      - name: Build JAR with Maven
        run: mvn clean package assembly:single

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}

      - name: Build Docker image
        run: docker build -t ${{secrets.DOCKERHUB_USERNAME}}/credit-simulator:latest

      - name: Push Docker image
        run: docker push ${{secrets.DOCKERHUB_USERNAME}}/credit-simulator:latest
